### ISSUE TITLE
How is this "better" than using OZ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#10]
http://hueniverse.com/2015/09/19/auth-to-see-the-wizard-or-i-wrote-an-oauth-replacement/
https://github.com/hueniverse/oz

**Comment by jalcine** [comment]
So Oz seems to be more of a layer for authenticating _client_ applications to an _API_ layer (provided that Hapi is the server). I think Oz could even be used for client side applications. However, if you use Hapi to handle page rendering as well, I don't think Oz would be the appropriate tool for the job there.

**Comment by nelsonic** [comment]
Agree. :+1: 
Just thought I would give Eran's post(s) a review before continuing. 
But I think we are going to deliver something *super useful*. :wink:

**Comment by jalcine** [comment]
So reviewing his article a few times, Oz seems to be a tool that can be plugged into or driven by hapi-login. *However*, I'm not immediately sure if a lot of work carried by Oz would be needed to be handled by hapi-login (the client side validation logic, for one). If anything, I can see hapi-login serving as a transitional tool from a classic setup to Oz.

**Comment by nelsonic** [comment]
Closing as not relevant anymore. 👍
