### ISSUE TITLE
CHORE: Fix SourceLevel Issues

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#104]
We are using SourceLevel to track untidy code in Auth.  (see: https://github.com/dwyl/technology-stack/issues/86)
At present there are 106 issues listed: https://app.sourcelevel.io/github/dwyl/auth [![SourceLevel](https://app.sourcelevel.io/github/dwyl/auth.svg)](https://app.sourcelevel.io/github/dwyl/auth)

Most of these issues are nit-picky things like:
CSS "Rule doesn't have all its properties in alphabetical order." 🙄   
https://app.sourcelevel.io/github/dwyl/auth/reviews/30 

![image](https://user-images.githubusercontent.com/194400/92570326-aae01c00-f279-11ea-9d48-b7e241502ea5.png)

While most of these issues are _super_ easy to fix, some will be a bit more complex.
If you have time to fix a couple and create a PR linking to this issue it's a good way to get to know the **`auth`** App's codebase and help tidy it up a bit. 
Definitely don't try and fix _all_ of them at once unless you have **`T4h`** "spare".
If we can aim to have all the issues fixed by the end of the month (Sept 2020) it would be great. 👍

**Comment by SimonLab** [comment]
From https://github.com/dwyl/technology-stack/issues/86#issuecomment-1217502890
> Tried it in https://github.com/dwyl/auth/issues/104, thought it was more pedantic than practical. Closing. :white_check_mark:

@nelsonic I think this issue can be closed?

**Comment by nelsonic** [comment]
Yeah, we can always re-open in the future. But for now `mix format` is enough. 👌
