### ISSUE TITLE
Include auth_url in AUTH_API_KEY ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#162]
While going through the steps of setting up a "dev" version of this app on Heroku so that we can have Review Apps https://github.com/dwyl/auth/issues/161, 
it occurred to me that Google includes a URL in their `GOOGLE_CLIENT_ID` ... 🤯 

https://github.com/dwyl/auth/blob/165571db283c467818673d85ffb345c171bd959a/.env_sample#L6

e.g:
```
88803175225-4hkccb841dh9ffvd2c0.apps.googleusercontent.com
```
**Note**: Just an example for illustration. Not a real/valid key. 🔑 

We could make the setup of `auth_plug` even easier because the `AUTH_API_KEY` could contain the `auth_url` 
and thus the **_single_ environment variable** becomes all that is needed for configuration!

This would require a fair amount of refactoring (2-3h with tests), but I think it's probably worth it! 💭 

@SimonLab Thoughts? 💭

**Comment by nelsonic** [comment]
Basically we can avoid hard-coding the `auth_url` in the `router.ex` of the "consumer" app:

https://github.com/dwyl/auth/blob/165571db283c467818673d85ffb345c171bd959a/lib/auth_web/router.ex#L36

Because the URL would be in the `AUTH_API_KEY` environment variable. 💭

**Comment by SimonLab** [comment]
Adding the redirect url in the environment variable should work. I don't find it to bothering to define the url in the plug config, I was using it to test redirection to other auth applications while developing/testing but I don't mind to switch to a full environment variable configuration.
Like you said there will be a bit of refactoring to do, not so much on `auth_plug` where we just need to extract the url once I think but mostly on `auth` where we need to make sure we don't break the way we get the client id and client secret.

**Comment by nelsonic** [comment]
OK. let's roll this Developer Experience improvement into the "V2" update. 💭

**Comment by nelsonic** [comment]
To give you an idea: the project I've been working on these last few months has **27 environment variables**. 
(_and even more secrets stored in AWS Secrets Manager ..._ 🙄)
It's an outlier because there are **_many_ 3rd party services** . But I think it could _easily_ have been reduced to 2 environment variables with a little bit of forethought which would have _significantly_ reduced Engineer onboarding time.

As for the environment variables required to get the **`auth_plug`** working ... My goal is to get it down to **one**. 

![image](https://user-images.githubusercontent.com/194400/141489312-b46769ec-3ea7-4b5e-9f3e-ef5609a12e29.png)
 

That way when people run the [**`dwyl/app`**](https://github.com/dwyl/app) on their `localhost` they can get setup in less than a minute and only have 1 thing they need to configure/set.
Thus minimising the friction/barrier to adoption & contribution. 
I know some people will consider this ["premature optimisation"](https://softwareengineering.stackexchange.com/questions/80084/is-premature-optimization-really-the-root-of-all-evil) to be thinking about the onboarding experience for new developers when our App isn't even built yet! But if the whole point of our App is to [**_never_ waste people's time**](https://github.com/dwyl/start-here/blob/master/manifesto.md#your-time-should-never-be-wasted) we need to be conscious of these _tiny_ details at every step.

**Comment by SimonLab** [comment]
I'm adding the auth_url on the app show page:

```html
<%= #{apikey.client_id}/#{apikey.client_secret}/#{auth_url} %> 
```
However using the "/" character to seperate the different parts of the key might not work nicely with the url (ie https://...). I'm thinking of using "-" instead
```
<%= #{apikey.client_id}/#{apikey.client_secret}-#{auth_url} %> 
```

**Comment by nelsonic** [comment]
@SimonLab yeah, was considering using the **`|`** (vertical bar or "pipe" character https://en.wikipedia.org/wiki/Vertical_bar ) because it is seldom used in URLs. Also the `auth_url` is just the _base_ URL so it should never contain a **`|`** (or at least we won't ever use it). 💭

**Comment by SimonLab** [comment]
sounds good, I don't mind to change "-" to "|". Or we could create an environment variable to configure this character in the app :wink:

**Comment by nelsonic** [comment]
@SimonLab i wasn’t going to use a fully qualified url (with the https:// ) as the protocol is just clutter. We will always connect over HTTPS so it will be omitted from the environment variable.

**Comment by SimonLab** [comment]
"https://" removed with https://github.com/dwyl/auth/pull/163/commits/01b19c2d02f332fb1ec0cd7ef6b4c2be703e6ce4

**Comment by nelsonic** [comment]
Thanks Simon! 🎉

**Comment by SimonLab** [comment]
The auth_url has been added to the api key with https://github.com/dwyl/auth/pull/163
