### ISSUE TITLE
Tests fail on `main` 🤷‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#164]
@SimonLab while working on my PR https://github.com/dwyl/auth/pull/159 I rebased on `main` after merging the recent PR #163 ...

I've updated the `AUTH_API_KEY` in my `.env` file to include the `dwylauth.herokuapp.com`

But when I run `mix test` I get the following error:

![image](https://user-images.githubusercontent.com/194400/143138082-c25f4a87-f9a1-47b7-9019-aa3999bf3d66.png)

Note: I have also run `mix deps.get` to and "All dependencies are up to date". 

Could you please confirm the tests pass for you on `main`?

The build badge linked from the `README.md` is the Travis one [![Build Status](https://img.shields.io/travis/dwyl/auth/master.svg?style=flat-square)](https://travis-ci.org/dwyl/auth) which we _know_ is not longer building ...
https://app.travis-ci.com/github/dwyl/auth

![image](https://user-images.githubusercontent.com/194400/143138578-4ee41c22-452c-434c-bd89-10c71f9c92cb.png)

As per https://github.com/dwyl/learn-travis/issues/67 🤦 

But the GitHub Actions CI: https://github.com/dwyl/auth/actions appears to be passing, e.g:
https://github.com/dwyl/auth/runs/4289064059?check_suite_focus=true
![image](https://user-images.githubusercontent.com/194400/143138754-ccceedf9-03fb-44e1-bf13-4ff424f09d86.png)

So I'm _guessing_ I am the one doing something wrong ... 🤷‍♂️ 
Could you please check that everything passes on your `main` branch on your `localhost`, please/thanks! 🤞

**Comment by SimonLab** [comment]
Hi @nelsonic , I've just cheded the main branch on my localhost and all the tests are passing. I had to recompile the dependencies first but now it's working. Make sure that the url in the api key doesn't end with `/`, ie `dwylauth.herokuapp.com` instead of `dwylauth.herokuapp.com/`

**Comment by nelsonic** [comment]
@SimonLab thanks very much for checking. 👍 
I think I will just have to do a fresh `git clone` and see if there is an issue on my side ... 💭

**Comment by nelsonic** [comment]
OK. I just did a fresh `git clone`, `cp /existing/auth/.env /tmp/auth/.env`, `mix deps.get` & `mix test` and it works: ✅ 
![image](https://user-images.githubusercontent.com/194400/143223504-c7eab246-8e0e-4145-93d2-b635f69803d1.png)

So I just need to figure out why it wasn't working in `CWD` ... ⏳

**Comment by nelsonic** [comment]
Figured it out ... 🔍 
Basically my `main` branch was "corrupted" with a change to `config/test.exs` ...
See: https://github.com/dwyl/auth/pull/159/files#r756824405 🤦‍♂️ 

Anyway, hopefully this won't be an issue again.
