### ISSUE TITLE
Internal Server Error at dwylauth.herokuapp.com

### ISSUE THREAD

**Issue by tadasajon** [dwyl/auth#165]
I went to the GitHub homepage for the auth app and clicked on the featured link.  I immediately got "Internal Server Error".

![Screen Shot 2021-11-29 at 11 00 12 AM](https://user-images.githubusercontent.com/86680401/143901239-4cb8f93d-cbb5-4046-890e-f816dd3f011e.png)

![Screen Shot 2021-11-29 at 10 57 03 AM](https://user-images.githubusercontent.com/86680401/143901271-c1309229-f479-43f2-bd73-0376decd00ce.png)

**Comment by SimonLab** [comment]
Log:
![image](https://user-images.githubusercontent.com/6057298/143902930-b624bc62-ac48-4e93-91a8-7151a9ae33c5.png)

**Comment by nelsonic** [comment]
@tadasajon could you please try https://authdev.herokuapp.com/ which has the latest enhancements we've been making #159 🤞

**Comment by tadasajon** [comment]
When I click on  https://authdev.herokuapp.com/  I get what looks like a properly-working auth app:

<img width="1191" alt="Screen Shot 2021-11-29 at 12 25 15 PM" src="https://user-images.githubusercontent.com/86680401/143914629-f4c64f8c-09d3-46e4-9ca1-de9a8f4aa3b9.png">

**Comment by nelsonic** [comment]
@tadasajon thanks for confirming the `dev` version is working as expected. 👍 
We are investigating why https://dwylauth.herokuapp.com/ is misbehaving. ⏳

**Comment by nelsonic** [comment]
PR to fix: #166 (just updates the version of `auth_plug` to latest).

**Comment by nelsonic** [comment]
The gist is this: the heroku App was still using the _old_ version of `AuthPlug.Token.client_id/0` 
so it wasn't splitting the `AUTH_API_KEY` environment variable properly ...

**Comment by nelsonic** [comment]
@tadasajon https://dwylauth.herokuapp.com/ should be working as expected now.
Apologies if there was an inconvenience caused. 

Perhaps we should have a disclaimer in the `README.md` to the effect of: 
"_If you have any questions/ideas or spot an error, please open an issue; we're here to help!_".
