### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth#181]
![image](https://user-images.githubusercontent.com/6057298/156340277-fea01b29-f71f-455a-8460-cf99c65e61c0.png)

Updating `mix.exs` file with the latest dependencies version produce conflict:
![image](https://user-images.githubusercontent.com/6057298/156340590-fc336a98-4330-4ab2-bee9-0f60591b4c80.png)

**Comment by nelsonic** [comment]
Done in #186 ✅ 
Thanks again @SimonLab 👍
