### ISSUE TITLE
Update Dependencies and Docs 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#186]
The dependencies are out-of-date so the `README.md` looks bad:

![image](https://user-images.githubusercontent.com/194400/157699400-bf56e797-5511-412c-92cf-42b28e4f9520.png)

https://libraries.io/hex/auth
![image](https://user-images.githubusercontent.com/194400/157699559-70bb81fc-c8af-441a-ba82-977f6fa7ca3a.png)

Also, we can mention the init page in the `README.md` as part of the setup process https://auth.dwyl.com/init

![image](https://user-images.githubusercontent.com/194400/157700211-6012bea2-63a8-42c5-a48e-aa9c4e63358d.png)

# Todo

+ [x] Update dependencies
+ [x] Update version in `mix.exs` so we can publish a new version.
+ [x] Update `README.md` setup instructions to include `/init` as a status check.

**Comment by SimonLab** [comment]
`mix hex.outdated`:
![image](https://user-images.githubusercontent.com/6057298/158142916-78a6c937-3a75-46e2-ba72-bf0090269d17.png)

We can also remove the warnings by using `import Config` instead of `user Mix.Config`

**Comment by nelsonic** [comment]
Thanks for looking at this @SimonLab please make the necessary updates if you have time or assign to me and I will take a look. 🤞

**Comment by SimonLab** [comment]
The PR #187 is now merged.
We just need to publish the newest version on hex for the dependencies badge to be updated.
@nelsonic I let you publish the latest version on hex once the deployment is finished to make sure everything work properly

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth/1.6.6 📦 🚀  (Thanks @SimonLab)

**Comment by nelsonic** [comment]
The badge usually takes a while to update ... ⏳

**Comment by nelsonic** [comment]
Libraries.io appears to have already picked up the update: https://libraries.io/hex/auth
<img width="928" alt="image" src="https://user-images.githubusercontent.com/194400/158157312-28e0f0ef-eee1-45ba-b8a7-5917bef617c7.png">

<img width="928" alt="image" src="https://user-images.githubusercontent.com/194400/158157366-72ed4d5a-07fa-45bb-a927-964d0b4b3de3.png">

https://github.com/dwyl/auth
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/194400/158157505-d518e0ec-6ef9-4c08-9cb8-4fc2c9d180d4.png">

But the badge:

[![Libraries.io dependency status](https://img.shields.io/librariesio/release/hex/auth?logoColor=brightgreen&style=flat-square)](https://libraries.io/hex/auth)

# 🤷‍♂️

**Comment by nelsonic** [comment]
All green! 🎉 
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/194400/158157688-c26bb9fe-bf6d-465c-b5c0-5e03f6caac78.png">

Thanks again @SimonLab 👍
