### ISSUE TITLE
Chore: Update License identifier in mix.exs

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#188]
At present when we run `mix hex.publish` we see the following message:

```
The following licenses are not recognized by SPDX:
 * GNU GPL v2.0

Consider using licenses from https://spdx.org/licenses
```

# Todo:

+ [ ] Update the license in `mix.exs` 
similar to: [github.com/michalmuskala/jason/blob/master/mix.exs#L61](https://github.com/michalmuskala/jason/blob/d5a75b93630ecd95fa4086edac9e85af14aefcc5/mix.exs#L61)

https://spdx.org/licenses/
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/194400/158154340-65367ca3-6d5e-44df-bbdd-bcce732cfdb3.png">

**Comment by nelsonic** [comment]
PR: #189 assigned to @SimonLab ⏳

**Comment by SimonLab** [comment]
Thanks for the update.
I wasn't sure what spdx means: https://en.wikipedia.org/wiki/Software_Package_Data_Exchange:

![image](https://user-images.githubusercontent.com/6057298/158156477-3eccfb19-c551-4d7e-96d7-b094c838dc51.png)

**Comment by nelsonic** [comment]
Yeah, I didn't know either. Googled it. Forgot to share the link. Thanks @SimonLab 🙌
