### ISSUE TITLE
Are we going to use OAUTH?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#2]
http://www.ibuildings.com/blog/2013/03/secure-your-rest-api-oauth2-implicit-grant

**Comment by eventhough** [comment]
What about [hawk](https://github.com/hueniverse/hawk) and [oz](https://github.com/hueniverse/oz)?

[http://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/](http://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/)

**Comment by nelsonic** [comment]
@eventhough Yeah, read Eran's post and agree with *most* of it. Just wanted to leave this as an open question. ultimately I don't think we want to be a login *provider* (*just yet*) because **dwyl** has *zero* reputation... but maybe others using this soon-to-be-launched Hapi Plugin might already have enough credibility to be an auth *provider*...

**Comment by nelsonic** [comment]
This module is an OAuth "_consumer_" but will not (_for the foreseable future_) implement the OAuth spec as an "identity provider". closing.
