### ISSUE TITLE
How To (End-to-End) Test Email?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#21]
I'm thinking of writing an AWS Lambda function that _receives_ an email and saves the _contents_ to AWS S3.
Then we can _read_ the file from S3 and _confirm_ that the contents is what we expect.
This would _prove_ that email is "working".

@iteles thoughts?

Note: it does _not_ prove "deliverability", but we expect AWS SES to handle that for us.

**Comment by iteles** [comment]
So far googling has not yielded any other suggestions and I don't have a better one.

From a user perspective, testing that an email is not marked as spam or that an email is delivered (as you say SES should handle that but does so poorly in our experience) would be the most useful tests, but this is part of the suite.

**Comment by nelsonic** [comment]
Coming soon to an AWS Account near you ... https://github.com/dwyl/aws-ses-lambda/pull/4#issuecomment-581173620
