### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by Danwhy** [dwyl/auth#23]
Our initial requirements for this module:

- Create an auth table/schema that is linked to a users table in the calling app. This means that we have some schema fields that we will define (`username/email`, `password`) but allows the developer using the module to define the fields that want their users to have. We'll need to make sure this works both with and without Append Only data.

- Signup functions - endpoints or controller functions that create both the user and auth table. This will need to use the relevant auth/user changeset functions for casting/verifying passwords etc.

- Encryption (see https://github.com/dwyl/phoenix-ecto-encryption-example) - encrypting user data for GDPR compliance.

- Auth plug - a plug (or multiple plugs) that will allow us to authorise users and check permissions (eg. Admin permissions, edit permissions)

@nelsonic Does this sound like we're thinking along the right lines? Anything you think we should also think about to begin with?

**Comment by nelsonic** [comment]
@Danwhy please see: https://github.com/dwyl/auth/issues/32 (_thanks!_)

**Comment by nelsonic** [comment]
All functionality described above is included in #43 
The **`auth_plug`** was created as a _separate_ reuseable package: https://github.com/dwyl/auth_plug

Thanks again for opening this issue @Danwhy 🙌
