### ISSUE TITLE
Bug: GitHub Username Not Returned by Auth ... 🤦‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#248]
As noted by @LuchoTurtle in https://github.com/dwyl/phoenix-chat-example/pull/120#issuecomment-1323509260 his `username` does not appear when he logs in via `Auth`. 

The GitHub `profile.login` should be set to the `person.username` by this line:
https://github.com/dwyl/auth/blob/f6a72102fd72f99ba8c42d00083e22c2fdec917a/lib/auth/person.ex#L126

But for some reason it's not appearing when @LuchoTurtle logs in on the Auth _Demo_ App: https://authdemo.fly.dev/people

<img width="776" alt="image" src="https://user-images.githubusercontent.com/194400/203516497-bbefc2ce-d15e-44df-895c-d4d3cabbc6b6.png">

This appears to be the case on the "prod" version of auth too: https://auth.dwyl.com/people/141
So we need to debug this stat! 👨‍💻 🔥

**Comment by nelsonic** [comment]
This is quite strange. I'm adding `dbg/1` statements to the `transform_github_profile_data_to_person/1` function to try and get to the bottom of this. 🤞

**Comment by nelsonic** [comment]
Not using latest version of `Elixir` on `auth` so got the following error: 
<img width="2663" alt="image" src="https://user-images.githubusercontent.com/194400/203518980-d3c8007c-8a0e-4c93-9a17-03ebf948f25e.png">


```
#24 2.585 == Compilation error in file lib/auth/person.ex ==
#24 2.585 ** (CompileError) lib/auth/person.ex:124: undefined function dbg/1
#24 2.585     (elixir 1.12.3) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
#24 2.585     (stdlib 3.16.1) erl_eval.erl:685: :erl_eval.do_apply/6
```

Need to go and find a line to update the `Dockerfile`:
https://github.com/dwyl/auth/blob/f6a72102fd72f99ba8c42d00083e22c2fdec917a/Dockerfile#L15

**Comment by nelsonic** [comment]
Borrowing `Dockerfile` from: https://github.com/dwyl/phoenix-chat-example/blob/baba16a988f65851c7c0c95ba2c2b31cfdb027e8/Dockerfile

**Comment by nelsonic** [comment]
@LuchoTurtle This is working for me on my localhost:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/194400/203554589-bb29a1e9-7070-43fe-bf85-ef8c67a29b0d.png">

Please confirm on your side by visiting: https://authdemo.fly.dev/people
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/194400/203554683-d59852fc-7005-4f07-839d-c67304d0b9d6.png">

Where you `person.username` is displayed in the `Username` column.

I logged the JWT on returned by `auth` ( https://authdemo.fly.dev ) and it includes the `username` now:

```elixir
%{
      app_id: 2,
      aud: "Joken",
      auth_provider: "github",
      email: "rex@gmail.com",
      exp: 1700745867,
      givenName: "Rex Dangervest",
      iat: 1669208867,
      id: 7,
      iss: "Joken",
      jti: "2sl3h7ncd22cnc3cck12h",
      nbf: 1669208867,
      picture: "https://avatars.githubusercontent.com/u/10835816?v=4",
      roles: "6,6",
      sid: 76,
      status: 1,
      username: "nkamc"
}
```

**Comment by LuchoTurtle** [comment]
This works on my side, it shows the username.

But I think there's something up in `auth_plug`, the username is not present at all. https://github.com/dwyl/phoenix-chat-example/pull/120#issuecomment-1325073845

This issue should be resolved in `auth`, but not so much in `auth_plug` 🤔

**Comment by LuchoTurtle** [comment]
Aaaaah, it works now.
I had to `Reset API key`

<img width="1137" alt="Screenshot 2022-11-23 at 13 36 35" src="https://user-images.githubusercontent.com/17494745/203560667-977278f5-b6e0-46b4-89ea-b65518072f0e.png">

So previous registered apps need to refresh so the JWT brings the `username`.

**Comment by nelsonic** [comment]
I didn't refresh my API key. But I'm glad that resetting yours worked. There aren't any other Apps using this `auth` instance so nobody `else` should see this issue in practice. 👌
