### ISSUE TITLE
Which login/authentication providers do we want to support?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#3]
@iteles do you have a list of services we would like to allow people to login with?
e.g:

![example range of logins](http://i.imgur.com/VVJ1pSr.png)

at the time of writing, https://github.com/hapijs/bell supports: 
![hapi-bell-login-supported](https://cloud.githubusercontent.com/assets/194400/7890383/9e89fd96-063d-11e5-8185-ac1da25bf54e.png)

**Comment by iteles** [comment]
We briefly discussed it the ones we wanted to [support for 'time' in this issue](https://github.com/dwyl/time/issues/36). I would say that for _our_ purposes, we want to keep it as simple as possible (both in terms of interface and general lack of complexity) so I would go with Google, Twitter and Facebook in the first instance.

I would sy GitHub and LinkedIn are also contenders and should be supported in this module. 
I would also add in Instagram for the module. 
It would be interesting to test usage of logins of the following for people who want to link stuff to thei online work (designers and bloggers for example):
+ [Dribbble](http://developer.dribbble.com)
+ [Behance](https://www.behance.net)
+ Popular blogging platform like [Wordpress](http://wp-api.org/) and [Typepad](http://www.typepad.com/services/apidocs) and [Blogger](https://developers.google.com/blogger/)

**Comment by nelsonic** [comment]
For the _first_ version of Auth (_and our App_) we are only going to support:
+ Email + Password Authentication
+ GitHub: https://github.com/dwyl/elixir-auth-github
+ Google: https://github.com/dwyl/elixir-auth-google

We will _consider_ adding other providers _later_ based on _feedback_ from people using the App and the _analytics_ data we collect on _actual_ usage for specific devices/platforms e.g: #37
