### ISSUE TITLE
[Epic] Roles, Permissions and Grants

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#31]
On Monday we drew out the _basic_ auth schema (_including Roles, Permissions and User_Roles_) on the witeboard in the Office together:

![auth-schema-whiteboard-diagram](https://user-images.githubusercontent.com/194400/53515937-077a4c80-3ac3-11e9-9b14-303480d034db.jpg)

This issue/epic is our attempt to _capture_ as much detail as we can so we can _implement_ it.

If you are _interested_ in this challenge, please read: [wikipedia.org/wiki/Role-based_access_control](https://en.wikipedia.org/wiki/Role-based_access_control)

More detail on the roles schema in https://github.com/dwyl/auth/issues/27#issuecomment-456214713
I will be adding it to here _shortly_ ⏳ 

# Todo

+ [x] Research and Write-up RBAC Systems #82

**Comment by nelsonic** [comment]
We don't need Roles, Permissions and Grants to manage access to content in the dwyl App for "single player mode", but it becomes _immediately_ relevant once someone wants to _share_ an item with anyone else. Do they want the other person to have read-only access, edit or co-own the item? This are all questions that can be answered/solved by an RBAC system.

My plan for today is to do a "deep dive" into RBAC from first principals and make notes on everything so that anyone **`else`** can understand what is going on with the system. I will then _build_ a reusable RBAC system that can be use for both the dwyl App and the @home security (access control) system: https://github.com/dwyl/smart-home-auth-server/issues/1

I don't expect my research/writeup phase to last more than a few hours, but I don't want to treat this superficially because it's a foundational concept that everyone needs _crystal_ clarity on. My intention is to write up an authoritative but still accessible (beginner-friendly) writeup similar to https://github.com/dwyl/learn-json-web-tokens

**Comment by th0mas** [comment]
@nelsonic Do you have an ETA on this?

**Comment by nelsonic** [comment]
Hi @th0mas, I got sidetracked researching how we can control the 20 doors without needing 20 RPi0s and 20 POE converters. 🔍  https://github.com/dwyl/smart-home-security-system/issues/14#issuecomment-659229046
Need to fix the failing Auth tests: https://github.com/dwyl/auth/issues/83#issuecomment-658850346
Then will be able to create the roles endpoint and add them to `JWT` quite quickly. 👍

**Comment by nelsonic** [comment]
ERD ***`before`*** RBAC:

![image](https://user-images.githubusercontent.com/194400/88185910-672f4580-cc2c-11ea-9381-1dbd3d266c15.png)

**Comment by nelsonic** [comment]
Auth ERD with Roles and Permissions:
![auth-erd-with-roles-permissions](https://user-images.githubusercontent.com/194400/88439166-5c2e0e00-ce02-11ea-93ce-11c3a721cb18.png)

**Comment by nelsonic** [comment]
Just the RBAC ERD:
![image](https://user-images.githubusercontent.com/194400/90513108-12adb600-e157-11ea-9419-9c09d432c92f.png)

**Comment by nelsonic** [comment]
Roles deployed to https://dwylauth.herokuapp.com/roles
RBAC for controlling access in apps: https://github.com/dwyl/rbac

Background/docs captured: https://github.com/dwyl/auth/blob/master/role-based-access-control.md

Closing. ✅
