### ISSUE TITLE
Responsive Email Confirmation/Password Reset Template

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#35]
In order to verify people's email address (_for "double opt-in"_) we need to send them an email with a link that they need to click in order to _verify_ their email address. 

+ [x] Create a template for sending emails that allow us to include a link.
  > We have done before for Healthlocker and TC please see:
https://github.com/dwyl/learn-phoenix-framework/blob/master/sending-emails.md
  > If there are any "gaps" in the setup/sending please update/clarify. (_thanks!_)
+ [x] Investigate _responsive_ email templates. (_please timebox this_)
  + [x] Include a Logo image in the email to reassure people that it's a legit email.
  + [x] include some basic styles 

@Cleop please work with @RobStallion on sending the "verify email address" email for Auth.
If you have _any_ questions, please comment. (_Thanks!_)

**Comment by Cleop** [comment]
Healthlocker email file:
https://github.com/healthlocker/healthlocker/blob/becff6feafb3e10ebe061f7056bcc04bf4755c0c/lib/email.ex

```
  def send_reset_email(to_email, token, host) do
    new_email()
    |> to(to_email)
    |> from(System.get_env("FROM_EMAIL"))
    |> subject("Healthlocker Reset Password Instructions")
    |> text_body("Please visit https://#{host}/password/#{token}/edit to reset your password")
  end
```

This example has `host` and `token` args that we could substitute for our 'link' argument.

What is not clear from this example is whether the text body can include html/css and the inclusion of media queries for responsiveness. I will look into this on Bamboo.

**Comment by nelsonic** [comment]
@Cleop great refer to HealthLocker. 🎉 (_much of this is re-useable_) 👍

**Comment by Cleop** [comment]
From Bamboo docs - https://hexdocs.pm/bamboo/readme.html#composing-with-pipes-for-default-from-address-default-layouts-etc:

>     |> put_html_layout({MyApp.LayoutView, "email.html"})

Looks like using this we can do both styling and html by adding the email content as a template.

**Comment by Cleop** [comment]
<img src="https://user-images.githubusercontent.com/16775804/54767503-2ae17480-4bf5-11e9-9301-b70d781115af.png" width="300px" />

**Comment by Cleop** [comment]
Responsive email templates:
- In-depth custom template tutorial: https://webdesign.tutsplus.com/articles/creating-a-simple-responsive-html-email--webdesign-12978
Key points:
- use premailer if putting styling in the `<head>`
- you can't just use media queries for responsive styling as it's not supported on all mail apps. Instead you need to use a combination of media queries, max width and if statements to create conditions for IE and Microsoft services. The articles gives a breakdown of each of these steps.
- 'Fluid'
- A couple of examples of templates that you can copy for free: https://tedgoas.github.io/Cerberus/

**Comment by Cleop** [comment]
Error for adding a link as an argument:
```
expected "assigns" to expand to an existing variable or be part of a match
```

Approach used:
https://stackoverflow.com/questions/44562513/email-templates-using-bamboo-without-phoenix

Docs for the `eval_file` fn (which works fine without adding the extra argument):
https://hexdocs.pm/eex/EEx.html#eval_file/3-examples

Example:
`EEx.eval_file "sample.eex", [bar: "baz"]           #=> "foo baz"`

Our code:
`EEx.eval_file("./lib/auth_web/templates/html_email/email.html.eex", foo: link)`

Thoughts:
- Is this to do with the fact that the example is without phoenix and so is this error something in phoenix disagreeing with our implementation of it?

**Comment by Cleop** [comment]
@SimonLab @Danwhy pointed out that:
`  use Bamboo.Phoenix, view: Auth.HtmlEmailView` should be `use Bamboo.Phoenix, view: AuthWeb.HtmlEmailView` and it now works in both contexts (with or without the extra assigned variable) 🎉

**Comment by nelsonic** [comment]
Elixir template: https://github.com/dwyl/auth/blob/master/lib/auth_web/templates/html_email/email.html.eex

Converting this to a Handlebars template so we can send it using #39 in #62
