### ISSUE TITLE
Auth Boss: Notes on authentication methodologies 🥇 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#38]
Just read through @teesloane's Auth Boss https://github.com/teesloane/Auth-Boss 📖 
it's _superb_ and I think we should link to it in the recommended reading section. 🔗

**Comment by teesloane** [comment]
Ah, thank you  for your kind words @nelsonic. I would be pleased to have it featured and of use in this repo.

**Comment by nelsonic** [comment]
@teesloane great work on the guide! 🎉 
Completely unrelated, do you have a pet Bunny?! 😮 🐇 

![image](https://user-images.githubusercontent.com/194400/73765685-cb3c7b00-476c-11ea-97e1-d5977bbafbcc.png)

**Comment by teesloane** [comment]
Sadly, no. The bunny in this photo is Ralphie, a rescue bunny, who is being take care of by a friend. This is a photo of us meeting for the first time.

**Comment by nelsonic** [comment]
Link added to readme: https://github.com/dwyl/auth/pull/123/commits/6b609815c3ed9871d00c4248e4cb45888a183e5d

✅
