### ISSUE TITLE
Replace Brunch by Webpack

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth#40]
Phoenix is now using Webpack for managing assets instead of Brunch.
We can try to upgrade this by changing the configuration in the asset folder:
https://github.com/dwyl/auth/blob/master/assets/brunch-config.js

**Comment by nelsonic** [comment]
@SimonLab switching from Brunch to Webpack is actually quite straightforward:
https://www.phoenixframework.org/blog/upgrading-from-13x-to-140 
(scroll down to: "Replace Brunch with webpack" section)

> I actually _preferred_ Brunch 🥑
But I can see _why_ the Phoenix team decided to use Webpack ... 📦 

_However_, I think we will be better off "gutting" this project and refreshing with a clean slate. ♻️ 
We now have [**`elixir-auth-github`**](https://github.com/dwyl/elixir-auth-github) and [**`elixir-auth-google`**](https://github.com/dwyl/elixir-auth-google) that implement a _lot_ of functionality. ⭐️ 
As soon as we have the [**`email`**](https://github.com/dwyl/auth/issues/39) Lambda Function [**`aws-ses-lambda`**](https://github.com/dwyl/aws-ses-lambda) working, 💌  
we will be able to re-do this quite _easily_.  By that I mean **`mix phx.new auth`** ... 🆕 
Which will be a _lot_ faster than having to delete/update a bunch of things. ⏩ 

We want to do a _lot_ more documentation for the **`auth`** project ***`while`*** building it,
similar to [dwyl/**phoenix-chat-example**](https://github.com/dwyl/phoenix-chat-example) 📝 
That way it will be a _lot_ easier for _complete beginners_ to understand & use the **`auth`** project. 🌱 

Our goal is that people building projects in **_other_ programming languages** can **_one-click_ deploy** **`auth`** so they can focus on the "core" features of their App and not _think_ about any **`auth`** code. 👩‍💻

**Comment by SimonLab** [comment]
Agree, starting from a fresh Phoenix project will be faster than trying to update/clean the current code.
It's also a good way to review all the requirements for auth (e,g. database structure, google/github auth, email/password, api endpoints)

**Comment by nelsonic** [comment]
Closing as Brunch will be removed by #43
