### ISSUE TITLE
Log all Login Attempts

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#67]
At present (pre-alpha!) we aren't logging _anything_. We need to log _everything_ in the Auth app to help mitigate malicious activity. 

The fields we want to log are: 
+ [x] `email` - encrypted email address of the person the login attempt was made for. This allows us to keep track of how many attempts were made for a given account in a set time frame. 
+ [x] `person_id` - if the email exists in our `people` table log the `person_id` otherwise just the `email` so that we can later analyse the _failed_ attempts. (e.g: typos)
+ [x] `ip_address` - so we can rate limit by `person_id` and `ip_address` and so that we can inform people when their account has been accessed from an unrecognised IP. 
see: https://github.com/dwyl/hits/blob/cd9a8e15c6e598281b7bc6b037963dab6ac515f8/lib/hits_web/controllers/hit_controller.ex#L32-L33
+ [x] `user_agent_id` - same as in Hits, we will have a `user_agents` schema where we store the full User Agent string then we reference it in the log rather than duplicating it.
> This will eventually be replaced by "Client Hints" for better privacy (_according to Google_) 🙄 
see: https://www.zdnet.com/article/google-to-phase-out-user-agent-strings-in-chrome )
+ [x] `auth_provider` - e.g. `google`, `github` or `email`
+ [x] `app_id` the app the person authenticated with relevant to #122 
+ [x] `timstamps` (_default in all Ecto/Phoenix schemas_)

This is related to our  _general_ quest to do Logging effectively in Phoenix Apps: https://github.com/dwyl/learn-devops/issues/60
I think it makes sense to do the API logging table _first_ and re-use it for this. https://github.com/dwyl/app/issues/274 💭

**Comment by SimonLab** [comment]
I was thinking of creating a plug that we can add to the endpoints we want to listen to.
The plug can extract the information from the headers and from the assigns value (we need to make sure that it is run after the assign values are set by other plug).

However I think we also want to save the information of the responses (at least the status codes).
I'm not sure yet if this is doable with a plug so I'm going to try some code and which information and where on the request/response life cycle we can access them with elixir.

**Comment by nelsonic** [comment]
@SimonLab if you are looking into this issue, 
please consider the more _general_ logging issue _first_: https://github.com/dwyl/app/issues/274 
and read the source of https://github.com/timberio/timber-elixir to see how they are doing it.  
Ref: https://github.com/dwyl/learn-devops/issues/60

**Comment by SimonLab** [comment]
Logging a response status might not be possible in every case to do directly inside a Phoenix application.
There is the [register_before_send](https://hexdocs.pm/plug/Plug.Conn.html#register_before_send/2) function:
![image](https://user-images.githubusercontent.com/6057298/81952602-95762080-95fe-11ea-823a-923b11c8b2f3.png)

However if the application fail before (e.g. error in a controller) the function might not be called
see: https://elixirforum.com/t/how-to-log-the-raw-http-response-built-by-phoenix-right-before-it-is-sent-to-the-client/19192/7

**Comment by nelsonic** [comment]
@SimonLab if the request is failing in the controller we should be able to _trace_ it in our logs.
Using `register_before_send` could be an option as _part_ of our logging. 👍

**Comment by SimonLab** [comment]
I've been reading the following articles:
- https://timber.io/blog/the-ultimate-guide-to-logging-in-elixir/
- https://www.verypossible.com/blog/thoughtful-logging-in-elixir-a-phoenix-story
- https://hexdocs.pm/logger/Logger.html

This mostly deal with `Logger` and how to configure and use it in your Elixir application.
The articles explain what are the different type of log levels (debug, info, warn, error) and how to select one. By default the `Logger` is using `debug`, however the configuration of each environment set the level (ie do not display debug on prod, only info, warn and error).

Logging can consume cpu and memory and can delay your application, for example when a complex datastructure is passed to `Logger` which requires to be analyse first. For that `Logger` provides some options:
- `sync_threshold`: define limit of message in queue where the log is not anymore asynchronous and become syncrhonous
- `discard_threshold`: discard messages above the define threshold (ie max number of log message in the queue)

You can configure the level of log at runtime with `Logger.configure` function, for example `Logger.configure(level: :debug)

`Logger` is able to used different [backend](https://hexdocs.pm/logger/Logger.html#module-backends). A backend is where the log is written, the default one is `console`.
My first thought to log all the login attempt was to create a customise backend which will writte the log automatically in Postgres. However for a first attempt this feel over engineer at the moment.
So I'm currently creating the tables `login_logs` and `user_agents` as describe on the first comment and will call the ecto query in the controller which manage the logins.

**Comment by nelsonic** [comment]
Working on this _today_ as it's required by https://github.com/dwyl/auth/issues/122 ⏳

**Comment by nelsonic** [comment]
Logging now enabled. Updated code, schemas and tests included in #123 ✅

**Comment by nelsonic** [comment]
Example of logs including both success and failure:
![image](https://user-images.githubusercontent.com/194400/94157343-09f88000-fe79-11ea-8512-c4cfee6baf9f.png)
