### ISSUE TITLE
Which database should be used for storing login credentials?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#7]
Suggestions are most welcome!

**Comment by jalcine** [comment]
So I feel for the highest compatibility between users's existing solution, a thin wrapper for fetching credentials might be best. AFAIK, object relational mappers in Node don't really follow a uniform approach for fetching information (Sequelize uses a Promise for any query actions, for example).

Perhaps something like in the options:
```javascript
{
   // awesome options here,
   fetch: function fetchCredientals(username, password) { }
}
```

Where `fetch` is a provided method that allows the developer to define the lookup work.

**Comment by nelsonic** [comment]
Thankfully, Phoenix uses PostgreSQL (_which we can "front" with Redis if we ever need to_)
so this is not an issue. 
closing.
