### ISSUE TITLE
Basic Authentication (Username/Email and Password)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#8]
Should we use https://github.com/hapijs/hapi-auth-basic
or can we _simplify_ it...? https://github.com/dwyl/time/issues/52

**Comment by jalcine** [comment]
Ah, I was curious if this was a `HTTP basic` or basic in the sense that all that's needed to be provided over a request is a `username` and `password`

---
I'm interested in refactoring _a lot_ of code (and hopefully deleting!) in favor of this plugin!

**Comment by nelsonic** [comment]
@jalcine you wish is my command. **ETA**: ***Next Thursday*** :wink:

**Comment by jalcine** [comment]
Haha, gotcha!

**Comment by nelsonic** [comment]
Issue with more detail: #63 
Included in PR #43 
Closing.
