### ISSUE TITLE
Signing into dwylauth.herokuapp.com sends a "Welcome to dwyl" email

### ISSUE THREAD

**Issue by th0mas** [dwyl/auth#81]
Everytime I log onto dwylauth.herokuapp.com I receive an email saying "Thanks for joining us to alpha test dwyl".
This is the same wether I log in using Github or email/password.

**Comment by nelsonic** [comment]
Yeah, this is intentional. Right now we assume everyone is "new" so we send them a welcome email.
An enhancement will be to only send the email when the person is authenticating for the _first_ time.

**Comment by th0mas** [comment]
As this is intentional, closing for now

**Comment by nelsonic** [comment]
@th0mas yeah, we could make it a "Welcome _Back_" Email or avoid sending one entirely if people have been using the App regularly. Or if our deliverability is being negatively affected ... but those are all future enhancements. 👍
