### ISSUE TITLE
Update Dependencies > Fix Failing Tests

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#83]
3 of our dependencies are out-of-date because _we_ published new versions of `fields` and auth_plug` and a new version of `plug_cowboy` was released.  https://libraries.io/hex/auth
![image](https://user-images.githubusercontent.com/194400/87411117-247fc480-c5bf-11ea-84c6-6a4487feb4be.png)

# Todo

+ [x] Update dependencies ***`before`*** working on RBAC #82 so we have a clean slate. 
+ [x] Fix failing tests ⬇️  https://github.com/dwyl/auth/issues/83#issuecomment-660049688

**Comment by nelsonic** [comment]
**`auth_plug`** had a **breaking change** where `AuthPlug.session_options/0` was removed in https://github.com/dwyl/auth_plug/pull/20/files#diff-1560d1759954bb80cc81c6769976610fL68
![image](https://user-images.githubusercontent.com/194400/87414288-79bdd500-c5c3-11ea-8a4f-bbf060525c34.png)


So now we need to a bit of refactoring in **`auth`** to _not_ invoke the unavailable function. 
![image](https://user-images.githubusercontent.com/194400/87413611-6c541b00-c5c2-11ea-86b8-820eb8c07ff9.png)

**Comment by th0mas** [comment]
Oops! Was there a particular reason why `Auth` was getting its session configuration from `auth-plug`?

**Comment by nelsonic** [comment]
@th0mas not really. it was just a way of keeping the **`auth`** App consistent with any app using **`auth_plug`**. ♻️ 
I figured that by _using_ **`auth_plug`** in **`auth`** I would immediately know if there was a breaking change. 💭 
In this case, there is, so now we get to do a bit more refactoring. 🔍  😉 
The starting point is: https://github.com/dwyl/auth_plug_example/issues/4
I'm happy to do this as it's a low-hanging fruit (chore) that I have all the environment variables setup for. 
I will assign the PR(s) to you though. 👍

**Comment by nelsonic** [comment]
After I made the same update to the `lib/auth_web/endpoint.ex` as in https://github.com/dwyl/auth_plug_example/pull/6/files#r454414361 the project _compiles_.
Unfortunately, 12 tests are failing with a similar-looking error:

```
  1) test delete apikey deletes chosen apikey (AuthWeb.ApikeyControllerTest)
     test/auth_web/controllers/apikey_controller_test.exs:204
     ** (ArgumentError) session not fetched, call fetch_session/2
     code: conn = AuthPlug.create_jwt_session(conn, person)
     stacktrace:
       (plug 1.10.3) lib/plug/conn.ex:1568: Plug.Conn.get_session/1
       (plug 1.10.3) lib/plug/conn.ex:1727: Plug.Conn.put_session/2
       (auth_plug 1.2.0) lib/auth_plug.ex:92: AuthPlug.create_session/3
       test/auth_web/controllers/apikey_controller_test.exs:206: (test)
```

Looking into it now.

**Comment by nelsonic** [comment]
It's not just the tests that fail on `localhost`, when I run the App it compiles but then Google Auth Fails:
![image](https://user-images.githubusercontent.com/194400/87648780-d34f0c80-c747-11ea-809d-1a3f37b5f75c.png)

If I _downgrade_ `auth_plug 1.2.0 => 1.1.1` and (and revert the change in `endpoint.ex`) 
then re-run the **tests** they all **pass** (_as expected_). 
But the Google Auth still fails:
<img width="1346" alt="auth-cowboy-error" src="https://user-images.githubusercontent.com/194400/87653770-ea90f880-c74d-11ea-9910-b0d61fe3d0c7.png">
 🤦 

From the stack trace I suspect this is a Cowboy issue (_using the incorrect version of TLS_).
So that's something `else` I will need to look at once the tests are passing with `auth_plug@v1.2.0`. 🙄 



> **Note**: I want to get onto [**`RBAC`**](#31) ASAP as I _know_ it's blocking progress in https://github.com/dwyl/smart-home-auth-server/issues/1 
but I want to have a solid foundation (_known working state_) _`before`_ adding anything new.

**Comment by nelsonic** [comment]
Still getting the error ... but this looks like a promising line of enquiry: https://elixirforum.com/t/erlang-v-23-0-and-httpoison-error/31615/7

**Comment by nelsonic** [comment]
On heroku the error is even _less_ helpful/friendly:
![image](https://user-images.githubusercontent.com/194400/87774808-f697bb80-c81c-11ea-8378-d8803aef94f5.png)

**Comment by nelsonic** [comment]
Ok after updating all the underlying dependencies, and making a few tweeks to the code,
we are back at a _known_ state with Auth. 
![image](https://user-images.githubusercontent.com/194400/87777153-e5e94480-c820-11ea-819d-6b1d42e88e5a.png)

![image](https://user-images.githubusercontent.com/194400/87777213-fdc0c880-c820-11ea-9758-f18ac3dd00e8.png)

![image](https://user-images.githubusercontent.com/194400/87777195-f699ba80-c820-11ea-932e-372c0f19de87.png)

![image](https://user-images.githubusercontent.com/194400/87777284-1f21b480-c821-11ea-9458-ceccaa7dda1f.png)

_However_ I still need to update to the latest version of `auth_plug` again and continue debugging that.

**Comment by nelsonic** [comment]
OK, back to `auth_plug@1.2.0` and debugging the error:

```
 12) test admin/2 show welcome page (AuthWeb.AuthControllerTest)
     test/auth_web/controllers/auth_controller_test.exs:16
     ** (ArgumentError) session not fetched, call fetch_session/2
     code: conn = AuthPlug.create_jwt_session(conn, Map.merge(data, %{id: person.id}))
     stacktrace:
       (plug 1.10.3) lib/plug/conn.ex:1568: Plug.Conn.get_session/1
       (plug 1.10.3) lib/plug/conn.ex:1727: Plug.Conn.put_session/2
       (auth_plug 1.2.0) lib/auth_plug.ex:92: AuthPlug.create_session/3
       test/auth_web/controllers/auth_controller_test.exs:25: (test)

.......

Finished in 17.8 seconds
1 property, 45 tests, 12 failures
```

The session needs to be started at the beginning of the request lifecycle to avoid seeing the error:
```
** (ArgumentError) session not fetched, call fetch_session/2
```

That's why we had:

https://github.com/dwyl/auth/blob/946f6ba58844798b32b2a81f5b1a246a3b396549/lib/auth_web/endpoint.ex#L40

I'm going to keep digging. ⏳

**Comment by nelsonic** [comment]
Ok, after a bit of digging, it turns out a new helper method was added to `Plug.Test` which we can use:
[`init_test_session/2`](https://hexdocs.pm/plug/Plug.Test.html#init_test_session/2) discovered via: https://github.com/phoenixframework/phoenix/issues/861#issuecomment-294711607

If we update a test from:

```elixir
test "lists all apikeys", %{conn: conn} do
  person = Auth.Person.get_person_by_email(@email)
  conn = AuthPlug.create_jwt_session(conn, %{email: @email, id: person.id})
  conn = get(conn, Routes.apikey_path(conn, :index))
  assert html_response(conn, 200) =~ "Auth API Keys"
end
```

To:

```elixir
test "lists all apikeys", %{conn: conn} do
  person = Auth.Person.get_person_by_email(@email)
  conn = conn
  |> init_test_session(foo: "bar") # auth/issues/83
  |> AuthPlug.create_jwt_session(%{email: @email, id: person.id})
  |> get(Routes.apikey_path(conn, :index))
  assert html_response(conn, 200) =~ "Auth API Keys"
end
```
It _passes_!! 🎉 
It's an extra line of code (_in each of the 12 tests_) but I'm fine with that because it reduces the number of steps to setup **`auth_plug`** as noted in: https://github.com/dwyl/auth_plug/pull/20/files#diff-04c6e90faac2675aa89e2176d2eec7d8

Going to make the changes to all the failing tests and see how far I get. 🤞

**Comment by nelsonic** [comment]
Applied the update to all 12 tests across 2 files. Works: 🙌 

![image](https://user-images.githubusercontent.com/194400/87782544-9dcf1f80-c82a-11ea-8b75-f02dc5fcd1b1.png)

**Comment by th0mas** [comment]
`init_test_session` is how we setup the session in `auth_plug` as well:   

```elixir
    setup %{endpoint: endpoint} do
      test_conn =
        conn(:get, "endpoint")
        |> init_test_session(%{})

      {:ok, conn: test_conn}
```

**Comment by th0mas** [comment]
To reduce LOC in tests, you can move `init_test_session/1` to the `conn_case` test helper, this is the strategy used in `dwyl/smart_home_auth`:

https://github.com/dwyl/smart-home-auth-server/blob/420ff63a009a0dbed7a17b23ea9f05ef85fbed9e/test/support/conn_case.ex#L43

**Comment by nelsonic** [comment]
@th0mas yeah, seen that _now_. ✅ 
https://github.com/dwyl/auth_plug/pull/20/files#diff-a8c2fcf60912e310ee9939d699ab98d4

**Comment by nelsonic** [comment]
@th0mas putting `init_test_session/1` in the `conn_case` is _much_ nicer. Thanks! 👍

**Comment by nelsonic** [comment]
@th0mas if you don't mind, please review/merg the PR: https://github.com/dwyl/auth/pull/84 Thanks! 🌻

**Comment by th0mas** [comment]
Done & merged
