### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by th0mas** [dwyl/auth#88]
Trying to access dwylauth.herokuapp.com results in a Heroku error message: 

![image](https://user-images.githubusercontent.com/9089056/88663433-80743e00-d0d3-11ea-886d-3d7ecb1426f4.png)

Is this related to dwyl/email#38?

**Comment by nelsonic** [comment]
Yeah, that's the same error, same account. Let's pay for the $7/month Dyno until we can shift all Apps to our own VPS. ⏳

**Comment by nelsonic** [comment]
```
heroku ps:type hobby

Scaling dynos on ⬢ dwylauth... done
type  size   qty  cost/mo
────  ─────  ───  ───────
web   Hobby  1    7
```

Paying the $7/month until I can switch the whole Auth/Email setup to an EC2 instance. 
Need to document how to run _multiple_ Phoenix Apps on the _same_ VPS: https://github.com/dwyl/learn-devops/issues/59

**Comment by nelsonic** [comment]
@th0mas you should be able to use https://dwylauth.herokuapp.com now.

**Comment by nelsonic** [comment]
no longer an issue. closing. 👍
