### ISSUE TITLE
How to insert additional data into a many_to_many lookup table?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#90]
Consider the following _simplified_ Database Entity Relationship Diagram (ERD) for a Role Based Access Control (RBAC) system:

![image](https://user-images.githubusercontent.com/194400/90631943-7ef1ed80-e21b-11ea-99ba-e7b3f794b792.png)

+ **`people`** are the _people using_ the system.
+ **`roles`** are the roles that **`people`** can have in the system.
+ **`people_roles`** is the `many_to_many` lookup table that allows people to have multiple roles.

> **Note**: this fits into the larger ERD https://github.com/dwyl/auth/issues/31#issuecomment-663761726 but I have removed the other tables from this diagram for simplicity as they are not relevant to _this_ discussion. 

In the `people` schema, we have the following `many_to_many` relationship defined:

```elixir
many_to_many :roles, Auth.Role, join_through: "people_roles"
```

https://github.com/dwyl/auth/blob/b27a21abca63499173636e2528feacf7ee979b02/lib/auth/person.ex#L23

That all seems fine so far. But when it comes to _inserting_ a record into the **`people_roles`** table we, 
want to have the concept of a **`granter_id`** the `id` of the `person` who granted the role. 

I have not found a way of doing this using idiomatic Ecto. 
Reading this "Many-to-many association table with extra columns" ElixirForum thread: https://elixirforum.com/t/many-to-many-association-table-with-extra-columns/6563 it seams to not be possible. 🤷‍♂️  I _really_ wish this was a _lot_ simpler. I feel like I'm tripping over the framework when trying to do something fairly simple/common. 

# Todo

+ [ ] Figure out how to insert a record into the **`people_roles`** table with the **`granter_id`** defined 
so that we have a clear audit trail of who granted which role to a given person.

**Comment by nelsonic** [comment]
Following the example in https://elixirforum.com/t/many-to-many-with-added-field/4994/2
I'm going to use the following approach and see how far I get:
```elixir
has_many :roles, through: [:people_roles, :role]
```

**Comment by th0mas** [comment]
Is `people_roles` defined as an Ecto schema? If so could you could:

``` elixir 
many_to_many :roles, Auth.Role, join_through: Auth.PeopleRoles
```

You could then do a `JOIN` query with PeopleRoles to get the required data? This may still require two database writes to start with though....

**Comment by nelsonic** [comment]
Debugging ...
![image](https://user-images.githubusercontent.com/194400/90663396-80cea780-e241-11ea-9c3a-b46c859f8a30.png)

**Comment by nelsonic** [comment]
OK, I think I've got it, thanks to both @th0mas' suggestion and a bit of persistence:

https://github.com/dwyl/auth/blob/5a0d8bfa88ecd7b9548ad48aa3298b3de1b8a22e/lib/auth/people_roles.ex#L11-L39
