### ISSUE TITLE
Restrict Access to Apps/API Keys

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth#99]
At present we allow anyone to view _any_ App/API Key:

https://github.com/dwyl/auth/blob/87c52d6da8191fcccda3526a84eb21ee4288621c/lib/auth_web/controllers/app_controller.ex#L27-L59

These are the default CRUD functions created in #95 
We need to allow only the person that created the App/API Key (_and the **`superadmin`**_) to view/edit/update/delete it. 

# Todo

+ [x] Create a helper function that automatically rejects the request if person is not allowed to view/edit/update/delete the content.

**Comment by nelsonic** [comment]
This is what I will be working on tomorrow morning ... ⏳ 
But for now ... 😴

**Comment by nelsonic** [comment]
A non-admin person should only be able to see their _own_ App(s) http://localhost:4000/apps
![image](https://user-images.githubusercontent.com/194400/92581036-0fee3e80-f287-11ea-860d-5a800d84f530.png)

Currently, they can see _everyone's_ Apps ... 
Let's _fix_ that!

**Comment by nelsonic** [comment]
non-admin can only see their own app:
![image](https://user-images.githubusercontent.com/194400/92715101-eef41f00-f354-11ea-9c74-f61cba9ca3a6.png)

Admin can see all apps:
![image](https://user-images.githubusercontent.com/194400/92715229-1d71fa00-f355-11ea-90ab-d72752475de8.png)

might add some detail to this table to help differentiate apps in the future.
But for now the restriction works which is what I wanted/needed. ✅

**Comment by th0mas** [comment]
Access to roles is not currently restricted, allowing anyone to create/edit/delete roles for any app - I'm guessing this isn't intended behaviour?

**Comment by nelsonic** [comment]
Hi @th0mas! longer-term we don't want _everyone_ seeing everyone _else's_  roles, agreed. 
If you don't mind, please open a new/separate issue specific to Roles so we can address it. 
Thanks! ☀️
